# Generated by Django 4.1.5 on 2023-03-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'bill_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('collective_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('passwd', models.CharField(max_length=50)),
                ('no_of_members', models.IntegerField()),
            ],
            options={
                'db_table': 'collective',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectivePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'collective_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectiveRawmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'collective_rawmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictHq',
            fields=[
                ('hq_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'district_hq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'district_warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'executive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preservative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'preservative',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fat_percent', models.IntegerField()),
                ('protein_percent', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('cost', models.IntegerField(db_column='Cost')),
                ('mrp', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('raw_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fat_percent', models.IntegerField()),
                ('protein_percent', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'raw_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawmaterialUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'rawmaterial_used',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('passwd', models.CharField(max_length=50)),
                ('profit', models.IntegerField()),
                ('manager_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'retailer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'retailer_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'retailer_warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'warehouse_batch',
                'managed': False,
            },
        ),
    ]
