# Generated by Django 4.2 on 2023-04-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksheer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
