# Generated by Django 4.2 on 2023-04-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksheer', '0002_alter_batch_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'managed': False},
        ),
    ]
